---
name: WWW-Shorten-Smallr
version: 0.01
author:
  - 'Dean Wilson <dean.wilson@gmail.com>'
abstract: Perl interface to Smallr.com
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  WWW::Shorten: 0
build_requires:
  Test::More: 0
provides:
  WWW::Shorten::Smallr:
    file: lib/WWW/Shorten/Smallr.pm
    version: 0.01
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
